[package]
name = "atom_modifier"
version = "0.1.0"
edition = "2021"
authors = ["thomjiji"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
aho-corasick = "1.1.1"
